VehicleDamage_FrontEnd/Controllers/ClockController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;
using VehicleDamage_FrontEnd.Models;
using VehicleDamage_FrontEnd.Models.Clock;
using VehicleDamage_FrontEnd.Models.DTOs;
using VehicleDamage_FrontEnd.Services.BEService;
using VehicleDamage_FrontEnd.Services.BlobService;
using VehicleDamage_FrontEnd.Services.DamageService;

namespace VehicleDamage_FrontEnd.Controllers
{
    public class ClockController : Controller
    {
        private readonly IDamageService _damageService;
        private readonly IBEService _vehicleService;
        private readonly IBlobService _blobService;

        /// <summary>
        /// Constructor for the controller that sets a context for each of the services.
        /// Which service is passed is controlled by the Enviornment in the startup
        /// </summary>
        /// <seealso cref="Startup"/>
        /// <param name="damService">Either fake or live AI Damage Service</param>
        /// <param name="veService">Either fake or live Back End Service</param>
        /// <param name="blService">Either fake or live blob stroage service</param>
        public ClockController(IDamageService damService, IBEService veService, IBlobService blService)
        {
            _damageService = damService;
            _vehicleService = veService;
            _blobService = blService;
        }

        /// <summary>
        /// Default route for the Clock Vehicle process.
        /// Empty model for the user to enter a Vehicle Liscence Plate.
        /// </summary>
        /// <seealso cref="Models.Clock.ClockModel"/>
        /// <returns>View of the ClockModel</returns>
        public IActionResult ClockVehicle()
        {
            ClockModel newModel = new ClockModel();

            return View(newModel);
        }

        /// <summary>
        /// Handles POST after the user has entered a an lplate number in the ClockVehicle Form.
        /// </summary>
        /// <seealso cref="ClockModel"/>
        /// <param name="model">ClockModel with the liscence plate field filled by the user</param>
        /// <returns>ClockVehicle view with the rest of the vehicle and clock details filled in</returns>
        // POST: Vehicle/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ClockVehicle(ClockModel model)
        {
            try
            {
                //Check liscence plate belongs to active vehicle
                VehicleDTO dto = await _vehicleService.GetVehicleAsync(model.vehicle.licenceNum);
                //If not found
                if (dto == null)
                {
                    //Reutn error
                    ModelState.AddModelError("vehicle.licenceNum", "Vehicle not found.");
                    return View(model);
                }
                //If there are any currently unresolved damage cases on the vehicle
                else if (dto.state == "Under Investigation")
                {
                    //Return error
                    ModelState.AddModelError("vehicle.licenceNum", "Vehicle currently unavailable due to potential damages. Please contact a member of staff.");
                    return View(model);
                }

                //Create model from the DTO
                ClockModel newModel = ClockModel.CreateModel(dto);
                //Return view with the update model
                return View(newModel);
            }
            catch
            {
                //Redirect tohe main blank page
                return RedirectToAction("ClockVehicle");
            }
        }

        /// <summary>
        /// After user confirms the form generated by the ClockVehicle Post method is correct.
        /// </summary>
        /// <seealso cref="ClockModel"/>
        /// <seealso cref="ClockVehicle(ClockModel)"/>
        /// <seealso cref="ImageDTO"/>
        /// <seealso cref="ImageDTO.GenerateImageId(Guid, string, string, IFormFile)"/>
        /// <param name="cModel">Clcok model with the details of the new state fileld out</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ConfirmClockVehicle(ClockModel cModel)
        {
            //Due to the lack of an auth/identitfy of the driver
            //This would is acting as a placeholder for the current driver ID
            Guid driverID = Guid.NewGuid();

            string updateResponse = null;

            //If clock in, check for damages against the AI service
            if (cModel.clock == "In")
            {
                //Generate a new ID for the potential damage model
                Guid damageID = Guid.NewGuid();

                //Create ImageDTO list for each image to be added as we go through the loop of uploads.
                List<ImageDTO> vehicleImages = new List<ImageDTO>();

                //Set state of tracking = null
                //Used to track the verdict. 
                //This allows to continue processing all uploaded images but still know that one showed damage
                string verdictTracker = "Undamaged";
                //Set counter to 0. This is used to add a suffix count to the end of the image filename when uploaded
                int count = 0;

                //Loop through uploads
                foreach(IFormFile img in cModel.imgs) 
                {
                    //Increment the count
                    count++;
                    //Create a new image DTO. 
                    ImageDTO newImageDTO = ImageDTO.CreateDTO(ImageDTO.GenerateImageId(damageID, cModel.time, count.ToString(), img), img);
                    vehicleImages.Add(newImageDTO);

                    try
                    {
                        //Check the damage of the images against the AI model
                        APIDTO returnApiDto = await _damageService.DamageCheckImg(newImageDTO);

                        //Extract at the decimal percentage of guesses for each tag
                        double damagedGuess = returnApiDto.predictions.FirstOrDefault(x => x.tagName == "Damaged").probability;
                        double wholeGuess = returnApiDto.predictions.FirstOrDefault(x => x.tagName == "Whole").probability;

                        //If both results are over 0.1 then cant say for certain. i.e level of uncertainty
                        //This is to make sure a Staff member will manually resolve it
                        if (wholeGuess >= 0.1 && damagedGuess >= 0.1)
                        {
                            //If not already set to damage from previous image.
                            //Test this because Damaged is a stronger case than Inclonclusive
                            if(verdictTracker == "Undamaged") 
                            {
                                verdictTracker = "Inconclusive";
                            }
                        }
                        //If the verdict is Damaged
                        else if (damagedGuess > wholeGuess)
                        {
                            //If Damaged then overrules the above conclusion of a previous image
                                verdictTracker = "Damaged";                          
                        }
                    }
                    catch 
                    {
                        //In any case of an error, set to Inclousive
                        verdictTracker = "Inconclusive";
                    }
                }

                //After loop of images, check the state.
                //If either damage or incloncsive
                if (verdictTracker != "Undamaged") 
                {
                    try 
                    { 
                        //Set the new state to
                        if (verdictTracker == "Inconclusive") 
                        {
                            cModel.clock = "Inconclusive";
                        }
                        //Damaged
                        else 
                        {
                            cModel.clock = "Damaged";
                        }

                        //Create and Insert a Damage history record to keep track of vehicle damages
                        DamageHistoryDTO newDamageDTO = DamageHistoryDTO.CreateDTO(DamageHistoryModel.CreateModel(cModel, damageID, driverID));
                         updateResponse = await _vehicleService.InsertDamageHistoryAsync(newDamageDTO);
                        if (updateResponse != "Success")
                        {
                            return RedirectToAction("ClockVehicle");
                        }

                        //Update Vehicle with new state
                        cModel.vehicle.state = "Under Investigation";
                        VehicleDTO newVehDto = VehicleDTO.CreateDTO(cModel.vehicle);
                        updateResponse = await _vehicleService.UpdateVehicleAsync(newVehDto);
                        if (updateResponse != "Success")
                        {
                            return RedirectToAction("ClockVehicle");
                        }

                        //Loop and upload images to blob storage
                        foreach(ImageDTO img in vehicleImages) 
                        {
                            //Save Images to the blob storage.
                            updateResponse = await _blobService.UploadImage(img);
                            if (updateResponse != "Success")
                            {
                                return RedirectToAction("ClockVehicle");
                            }
                        }

                        //Return back to confirmed view
                        return View("ClockConfirmed", cModel);

VehicleDamage_FrontEnd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Vehicle Damage</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        body, h1, h2, h3, h4, h5, h6 {
            font-family: "Raleway", sans-serif
        }

        body, html {
            height: 100%;
            line-height: 1.8;
        }

        .w3-bar .w3-button {
            padding: 16px;
        }
    </style>
</head>

<body>
    <header>
        <!-- Main Navbar -->
        <div class="w3-top">
            <div class="w3-bar w3-white w3-card" id="myNavbar">
                <a href="@Url.Action("Index", "Home")" class="w3-bar-item w3-button w3-wide">Vehicle Damage</a>
                <!-- Right-sided navbar links -->
                <div class="w3-right w3-hide-small">
                    <a href="@Url.Action("ClockVehicle", "Clock")" class="w3-bar-item w3-button">Clock Vehicle</a>
                    <div class="w3-dropdown-hover">
                        <button class="w3-button" title="Notifications">Staff <i class="fa fa-caret-down"></i></button>
                        <div class="w3-dropdown-content w3-card-4 w3-bar-block">
                            <a href="@Url.Action("Index", "Vehicle")" class="w3-bar-item w3-button">Vehicles</a>
                            <a href="#" class="w3-bar-item w3-button">Drivers</a>
                        </div>
                    </div>
                    <div class="w3-dropdown-hover">
                        <button class="w3-button" title="Notifications">Admin <i class="fa fa-caret-down"></i></button>
                        <div class="w3-dropdown-content w3-card-4 w3-bar-block">
                            <a href="#" class="w3-bar-item w3-button">Staff</a>
                        </div>
                    </div>
                </div>
                <!-- Hide right-floated links on small screens and replace them with a menu icon -->
                <a class="w3-bar-item w3-button w3-right w3-hide-large w3-hide-medium" onclick="w3_open()">
                    <i class="fa fa-bars"></i>
                </a>

            </div>

            <!-- Sidebar on small screens when clicking the menu icon -->
            <nav class="w3-sidebar w3-bar-block w3-black w3-card w3-animate-left w3-hide-medium w3-hide-large" style="display:none" id="mySidebar">
                <a href="javascript:void(0)" onclick="w3_close()" class="w3-bar-item w3-button w3-large w3-padding-16">Close ×</a>
                <a href="#about" onclick="w3_close()" class="w3-bar-item w3-button">Clock Vehicle</a>
                <a href="#team" onclick="w3_close()" class="w3-bar-item w3-button">Vehicles</a>
                <a href="#work" onclick="w3_close()" class="w3-bar-item w3-button">Drivers</a>
                <a href="#pricing" onclick="w3_close()" class="w3-bar-item w3-button">Staff</a>
            </nav>
        </div>
    </header>


    <div class="container w3-content w3-padding" style="margin-top:80px">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - VehicleDamage_FrontEnd - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)

    <script>

        // Toggle between showing and hiding the sidebar when clicking the menu icon
        var mySidebar = document.getElementById("mySidebar");

        function w3_open() {
            if (mySidebar.style.display === 'block') {
                mySidebar.style.display = 'none';
            } else {
                mySidebar.style.display = 'block';
            }
        }

        // Close the sidebar with the close button
        function w3_close() {
            mySidebar.style.display = "none";
        }
    </script>


</body>
</html>